# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62a138dca44c84044ae071ffce35373e9266c939a993fc737d3ff22a628ab6f43379cd8cf1239097b1a12e8c10329f1e699f279c7111addf2c1626bacd97062f

test:
  secret_key_base: fdc52ffa5c5aff6b6bdbc6b2bf9c0d25bbcac555c77110dc3bdda4fb066b2725b3180996dc7a3d7d93e9e8582ff40c71a26bb3331cd19abe7f2d698bf089f17b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
